spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
    username: customer_user
    password: customer_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

logging:
  level:
    root: INFO